### ISSUE TITLE
Implementation Tracker: Basic, EIP, and Intermediate

### ISSUE THREAD

**Issue by hermanjunge** [sigp/rust-bls-remote-signer#1]
- [x] **Basic implementation**
  - [x] Executable boilerplate
  - [x] Actual HTTP API server
    - [x] Server boilerplate
      - [x] Allow for configuration of `listen_address` and `port`
    - [x] Implement `/upcheck`
    - [x] Implement `/publicKeys` (respond NOT IMPLEMENTED)
    - [x] Implement `/sign/:public_key` (respond NOT IMPLEMENTED and the key sent)
    - [x] Respond 404 for everything else
  - [x] Backend
    - [x] Generic crate
      - [x] CLI option for `--storage-raw-dir` and pass it to the client
    - [x] Raw files storage
      - [x] Document how to prepare the raw files in this repositories' README
      - [x] Implement `/publicKeys` response
      - [x] Implement `/sign/:public_key`
  - [x] CI/CD pipeline
- [x] **Produce an EIP for the API**
  - [x] Write EIP draft into this repository
  - [x] Publish Pull request on EIP github repository
- [ ] **Intermediate implementation**
  - [x] Allow to opt between `milagro` and `blst` libraries
  - [x] Zeroize secret key after use
  - [ ] Metrics
  - [ ] Benchmarking & Profiling
  - [ ] Release management 
  - [ ] Architecture builds

**Comment by hermanjunge** [comment]
The tracker should cover up to `Intermediate`. To me, there are some advanced features, such as the ability to compile and run in Trusted Execution Environments (TEE), that need to be considered in the future.

**Comment by hermanjunge** [comment]
Moving this repository contents to https://github.com/sigp/lighthouse
